export type Film = {
  id: string;
  title: string;
  brand: string;
  year: string;
  category: string;
  poster: string;
  video: string; // YouTube video ID
  description?: string;
};

// YouTube video IDs for the popup player
export const films: Film[] = [
  {
    id: "f1",
    title: "AVT Onam",
    brand: "AVT",
    year: "2024",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/11/1.18.1_1.18.1-scaled.jpg",
    video: "f6fw-E6antE",
    //description: "A heartwarming Onam film for AVT, blending action and drama with festive emotion.",
  },
  {
    id: "f2",
    title: "Yeahhhhh..... Hooooooo Diwali",
    brand: "Manappuram Finance",
    year: "2024",
    category: "Brand Film",
    poster: "https://i.ytimg.com/vi/_KBqYgNyusU/mqdefault.jpg",
    video: "_KBqYgNyusU",
    //description: "Following three riders across the Himalayas — a 9-minute story of friendship.",
  },
  {
    id: "f3",
    title: "Fastest ISP in Kerala",
    brand: "Kerala Vision Broadband",
    year: "2024",
    category: "Digital",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_5971-scaled.jpg",
    video: "vuiznrLLx7k",
    //description: "Heritage meets modern craft. A tactile, intimate portrait of Indian tailoring.",
  },
  {
    id: "f4",
    title: "KBFC Association with Suguna Delfrez",
    brand: "Suguna Delfrez",
    year: "2022",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9022.jpeg.jpg",
    video: "w74Wjrw9B-s",
    //description: "Six cities. Six stories. One quiet moment before the world wakes up.",
  },
  {
    id: "f5",
    title: "Eatapioca Bride Film",
    brand: "Southern Hills",
    year: "2025",
    category: "Sports",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2023/11/1_1.14.1.jpeg",
    video: "o71MjLjdLec",
    //description: "Shot at 240fps — the heartbeat of athletes pushing past their limits.",
  },
  {
    id: "f6",
    title: "Eatapioca Youngster Film",
    brand: "Southern Hills",
    year: "2023",
    category: "Brand Film",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/1_1.40.1.jpeg.jpg",
    video: "pC7L6OW3PvU",
    //description: "A grandmother. A granddaughter. A necklace that travels through time.",
  },
  {
    id: "f7",
    title: "Vesta Ice Crush",
    brand: "Vesta Ice Cream",
    year: "2024",
    category: "Documentary",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2023/11/IMG_2376.jpeg",
    video: "ClAvTLqfcII",
    //description: "How a single bulb changed a village. A 14-minute documentary short.",
  },
  {
    id: "f8",
    title: "Vesta Tender Coconut Ice Cream",
    brand: "Vesta Ice Cream",
    year: "2025",
    category: "Sports",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9024.jpeg.jpg",
    video: "_jFSPf5r8S4",
    //description: "Grassroots football across India — kids, dust, and impossible dreams.",
  },
  {
    id: "f9",
    title: "Playful Treat",
    brand: "Vesta Ice Cream",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_2383.jpeg.jpg",
    video: "gUtb7d7xGqI",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f10",
    title: "Entri Elevate Supply Anthem",
    brand: "Entri App",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9020.jpeg.jpg",
    video: "wqZEFJzW2l4",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f11",
    title: "BSC Textile Mall",
    brand: "BS Channabasappa & Sons",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9026.jpeg.jpg",
    video: "p9r6QfMT58k",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f12",
    title: "Brilliance In Every Bloom",
    brand: "Sunny Diamonds",
    year: "2023",
    category: "TVC",
    poster: "https://i.ytimg.com/vi/-Q4DHdtBJso/mqdefault.jpg",
    video: "-Q4DHdtBJso",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f13",
    title: "Sunny Diamonds - Diwali Films",
    brand: "Sunny Diamonds",
    year: "2023",
    category: "TVC",
    poster: "https://i.ytimg.com/vi/XF2gFatf4HQ/mqdefault.jpg",
    video: "XF2gFatf4HQ",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f14",
    title: "The Joy of Dressing",
    brand: "Dawn Aesthetics",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9029.jpeg.jpg",
    video: "8Zu0YJNnXW0",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f15",
    title: "Women's Day Music Video",
    brand: "WCD Kerala - Government of Kerala",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9052.jpeg.jpg",
    video: "cqICADcyoyI",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f16",
    title: "Covid awareness film (Director's cut)",
    brand: "Amrita Hospital",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9047.jpeg.jpg",
    video: "BqANWOKxD4s",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f17",
    title: "Work from Home",
    brand: "Neck-Flix Pillows from PPG Group",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9042.jpeg.jpg",
    video: "HRAZMkT4Kig",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f18",
    title: "Screen Time",
    brand: "Neck-Flix Pillows from PPG Group",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9043.jpeg.jpg",
    video: "iy1shSZZUqE",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f19",
    title: "Online Class",
    brand: "Neck-Flix Pillows from PPG Group",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9044.jpeg.jpg",
    video: "d9SrTJ4SYKQ",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f20",
    title: "Kanchana Sambar Master Film",
    brand: "Kanchana Food Products",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9049.jpeg.jpg",
    video: "OgmQMgIZ7EY",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f21",
    title: "Kanchana Paayasam Master Film",
    brand: "Kanchana Food Products",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9040.jpeg.jpg",
    video: "MohcRtl60Ao",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },
  {
    id: "f22",
    title: "N'Style Home Collections",
    brand: "N'Style",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9041.jpeg.jpg",
    video: "Am5ncdv6c74",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },  
  {
    id: "f23",
    title: "ഇനിയും മുന്നോട്ട്",
    brand: "Government of Kerala",
    year: "2023",
    category: "TVC",
    poster: "https://firstpictureshowcompany.com/en/wp-content/uploads/2024/05/IMG_9038.jpeg.jpg",
    video: "EY3pkyh0wzQ",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },  
  {
    id: "f24",
    title: "Light on you, rich with love.",
    brand: "Celant by Bhima Jewellery",
    year: "2023",
    category: "TVC",
    poster: "https://i.ytimg.com/vi/_krB9l_bqag/mqdefault.jpg",
    video: "_krB9l_bqag",
    //description: "From the coasts of Gujarat to every Indian kitchen. A 60-second epic.",
  },  
];

export const awards = [
  { year: "2025", title: "Cannes Lions — Bronze", category: "Film Craft", project: "Pulse / Nike" },
  { year: "2025", title: "Kyoorius Creative Awards", category: "Best Direction", project: "Echoes of Tomorrow" },
  { year: "2024", title: "Spikes Asia — Gold", category: "Cinematography", project: "The Long Road Home" },
  { year: "2024", title: "Abby Awards", category: "Best Branded Content", project: "Threads / Raymond" },
  { year: "2024", title: "AdFest", category: "Silver — Direction", project: "Morning Ritual" },
  { year: "2023", title: "Goafest Creative Abby", category: "Gold — Production", project: "Heirloom / Tanishq" },
];

export const news = [
  { date: "Mar 2026", title: "FPSC opens a new post-production studio in Bandra West." },
  { date: "Jan 2026", title: "Our directors featured in Little Black Book's Asia Hot List." },
  { date: "Nov 2025", title: "FPSC signs Director Maya Iyer to its global roster." },
  { date: "Sep 2025", title: "Partnership with Arri Rental India for exclusive ALEXA 35 access." },
];

export const brands = [
  { name: "AVT", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/avt.png" },
  { name: "Manappuram", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/manappuram.png" },
  { name: "Kerala Vision", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/keralavision.png" },
  { name: "Suguna Foods", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/delfrez.png" },
  { name: "Southern Hill", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/southernhills.png" },
  { name: "Entri App", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/entri.svg" },
  { name: "Vesta Ice Cream", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/vesta.svg" },
  { name: "B.S Channabasappa & Sons", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/BSC.webp" },
  { name: "Sunny Diamonds", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/sunnydiamonds.svg" },
  { name: "Dawn Aesthetics", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/dawn-logo.avif" },
  { name: "Neckflix", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/neckflixpillows.png" },
  { name: "Kanchana Food Products", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/kanchanafoodproducts.png" },
  { name: "N'Style", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/NStyle.png" },
  { name: "Celant", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/celant.webp" },
  { name: "Celant", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/south-indian-bank.png" },
  { name: "Fazyo", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/fazyo.avif" },
  { name: "Bhima & Brother Jewellers", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/bhima-brother.png" },
  { name: "Treet", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/treet.webp" },
];

export const agencies = [
  { name: "Maitri", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/maitri-logo-svg.svg" },
  { name: "Adsyndicate", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/adsyndicate.png" },
  { name: "Meetha Paan", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/design.png" },
  { name: "Spark Consulting", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/sparkconsulting.png" },
  { name: "Open Creatives", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/Open_logo@4x.png" },
  { name: "White Waves Media", logo: "https://onlineyuga.co/First-Picture-Show-Company/src/assets/brands/WWM.png" },
];
